### ISSUE TITLE
support jruby

### ISSUE THREAD

**Issue by michaelachrisco** [Keeguon/tapsoob#4]
I added tapsoob as:
```Ruby
#Gemfile 
gem 'tabsoob', :git => 'https://github.com/Keeguon/tapsoob.git'
```
```Bash
bundle install
Fetching https://github.com/Keeguon/tapsoob.git
Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies...
Could not find gem 'tabsoob (>= 0) java' in
https://github.com/Keeguon/tapsoob.git (at master).
Source does not contain any versions of 'tabsoob (>= 0) java'
```

**Comment by Keeguon** [comment]
Hey,

Seems odd. I'll run tests first thing in the morning (Paris timezone) and
get back to you ;)!

On Monday, January 12, 2015, michael chrisco <notifications@github.com>
wrote:

> I added tapsoob as:
>
> #Gemfile gem 'tabsoob', :git => 'https://github.com/Keeguon/tapsoob.git'
>
> bundle install
> Fetching https://github.com/Keeguon/tapsoob.git
> Fetching gem metadata from https://rubygems.org/.........
> Resolving dependencies...
> Could not find gem 'tabsoob (>= 0) java' inhttps://github.com/Keeguon/tapsoob.git (at master).
> Source does not contain any versions of 'tabsoob (>= 0) java'
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Keeguon/tapsoob/issues/4>.
>


-- 
Félix Bellanger
122 Rue Marcadet
75018 Paris, France
Email: felix.bellanger@gmail.com
Twitter: @keeguon <http://twitter.com/keeguon>
Phone: +33.6.78.53.28.15
